<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
  <xsl:output method="html" encoding="UTF-8" indent="yes"/>
  
  <xsl:template match="/">
    <html>
      <head>
        <title>XML Sitemap</title>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <style>
          body {
            font-family: Verdana, Geneva, sans-serif;
            font-size: 13px;
            margin: 20px;
            background-color: #fff;
            color: #333;
          }
          h1 {
            font-size: 24px;
            margin: 0 0 15px 0;
            color: #333;
          }
          .description {
            margin-bottom: 20px;
            line-height: 1.5;
          }
          .description p {
            margin: 8px 0;
          }
          a {
            color: #1e8cbe;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          table {
            border-collapse: collapse;
            width: 100%;
            margin-top: 20px;
          }
          th, td {
            text-align: left;
            padding: 8px 12px;
            border-bottom: 1px solid #ddd;
          }
          th {
            background-color: #f0f0f0;
            font-weight: bold;
          }
          tr:hover {
            background-color: #f5f5f5;
          }
          .url {
            word-break: break-all;
          }
          .lastmod {
            white-space: nowrap;
          }
        </style>
      </head>
      <body>
        <h1>XML Sitemap</h1>
        
        <div class="description">
          <p>Generated by <strong>Saski AI</strong>, this is an XML Sitemap, meant for consumption by search engines.</p>
          <p>You can find more information about XML sitemaps on <a href="https://sitemaps.org" target="_blank">sitemaps.org</a>.</p>
          <p>This XML Sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.</p>
        </div>
        
        <table>
          <thead>
            <tr>
              <th>URL</th>
              <th>Last Modified</th>
            </tr>
          </thead>
          <tbody>
            <xsl:for-each select="sitemap:urlset/sitemap:url">
              <xsl:sort select="sitemap:priority" order="descending"/>
              <tr>
                <td class="url">
                  <a href="{sitemap:loc}">
                    <xsl:value-of select="sitemap:loc"/>
                  </a>
                </td>
                <td class="lastmod">
                  <xsl:value-of select="substring-before(sitemap:lastmod, 'T')"/>&#160;<xsl:value-of select="substring(sitemap:lastmod, 12, 8)"/>&#160;+00:00
                </td>
              </tr>
            </xsl:for-each>
          </tbody>
        </table>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet> 